// Orbit Company Intelligence Registry
// 500+ companies across all major tech categories

export interface Company {
  id: string;
  name: string;
  categories: string[]; // "faang" | "ai" | "saas" | "devtools" | "fintech" | "indian" | "yc" | "design" | "infra" | "remote"
  skills: string[];     // skills this company values most
  roles: string[];      // typical roles they hire for
  location: string;
  remoteType: "remote" | "hybrid" | "onsite";
  salaryRange: string;
  hiringIntensity: "very_high" | "high" | "medium" | "low";
  interviewDifficulty: "elite" | "hard" | "medium" | "accessible";
  aiAdoption: "native" | "heavy" | "moderate" | "low";
  growthVelocity: "hypergrowth" | "fast" | "steady" | "established";
  internFriendly: boolean;
  remoteFriendly: boolean;
  url: string;
  tags: string[];
}

export const COMPANIES: Company[] = [
  // ─── FAANG / Big Tech ───────────────────────────────────────────────────
  { id: "google", name: "Google", categories: ["faang","product"], skills: ["Python","Java","Algorithms","System Design","React","Go","Kubernetes","Product Thinking"], roles: ["Software Engineer","Frontend Engineer","ML Engineer","SRE","Product Manager","Associate PM"], location: "Mountain View, CA", remoteType: "hybrid", salaryRange: "$180k–$280k", hiringIntensity: "very_high", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://careers.google.com", tags: ["FAANG","Scale","Prestige","PM"] },
  { id: "meta", name: "Meta", categories: ["faang","product"], skills: ["React","C++","Python","System Design","ML","GraphQL","Product Strategy"], roles: ["Software Engineer","Frontend Engineer","ML Engineer","Research Scientist","Product Manager","RPM"], location: "Menlo Park, CA", remoteType: "hybrid", salaryRange: "$190k–$300k", hiringIntensity: "high", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://metacareers.com", tags: ["FAANG","AR/VR","Social","PM"] },
  { id: "apple", name: "Apple", categories: ["faang","product"], skills: ["Swift","Objective-C","C++","System Design","Machine Learning","iOS","Product Design"], roles: ["iOS Engineer","Software Engineer","ML Engineer","HW/SW Engineer","Product Manager","Technical PM"], location: "Cupertino, CA", remoteType: "onsite", salaryRange: "$185k–$290k", hiringIntensity: "medium", interviewDifficulty: "elite", aiAdoption: "heavy", growthVelocity: "established", internFriendly: true, remoteFriendly: false, url: "https://apple.com/careers", tags: ["FAANG","Consumer","Hardware","PM"] },
  { id: "netflix", name: "Netflix", categories: ["faang","product"], skills: ["Java","Python","System Design","Microservices","React","AWS","Kafka","Product Strategy"], roles: ["Software Engineer","Data Engineer","ML Engineer","Platform Engineer","Product Manager"], location: "Los Gatos, CA", remoteType: "hybrid", salaryRange: "$220k–$350k", hiringIntensity: "medium", interviewDifficulty: "elite", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://jobs.netflix.com", tags: ["FAANG","Streaming","Freedom & Responsibility"] },
  { id: "amazon", name: "Amazon", categories: ["faang","product"], skills: ["Java","Python","AWS","System Design","Algorithms","Leadership Principles","Product Management"], roles: ["Software Engineer","Cloud Engineer","ML Engineer","SDE","Product Manager","Technical PM","APM"], location: "Seattle, WA", remoteType: "hybrid", salaryRange: "$170k–$260k", hiringIntensity: "very_high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://amazon.jobs", tags: ["FAANG","Cloud","E-commerce","PM"] },
  { id: "microsoft", name: "Microsoft", categories: ["faang","product"], skills: ["C#","TypeScript","Azure","React","Python","System Design","AI","Product Thinking"], roles: ["Software Engineer","Frontend Engineer","Cloud Engineer","PM","Product Manager","Group PM","APM"], location: "Redmond, WA", remoteType: "hybrid", salaryRange: "$175k–$270k", hiringIntensity: "very_high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://careers.microsoft.com", tags: ["FAANG","Enterprise","Azure","PM"] },
  { id: "uber", name: "Uber", categories: ["faang","product"], skills: ["Go","Python","React","System Design","Kafka","Microservices","Data","Product Strategy"], roles: ["Software Engineer","Frontend Engineer","Data Engineer","ML Engineer","Product Manager","Technical PM"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$260k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://uber.com/careers", tags: ["FAANG-adjacent","Marketplace","Logistics","PM"] },
  { id: "airbnb", name: "Airbnb", categories: ["faang","product"], skills: ["React","Ruby","TypeScript","System Design","Data","Swift","Product Design"], roles: ["Frontend Engineer","Software Engineer","Data Scientist","iOS Engineer","Product Manager","Product Designer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$180k–$270k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://careers.airbnb.com", tags: ["FAANG-adjacent","Marketplace","Design","PM"] },
  { id: "twitter_x", name: "X (Twitter)", categories: ["faang"], skills: ["Scala","React","Java","Distributed Systems","ML","TypeScript"], roles: ["Software Engineer","ML Engineer","Infrastructure Engineer","Product Manager"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$170k–$250k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: false, url: "https://careers.x.com", tags: ["Social","Distributed Systems"] },
  { id: "linkedin", name: "LinkedIn", categories: ["faang","product"], skills: ["Java","React","Python","System Design","ML","Scala","Product Analytics"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","Data Engineer","Product Manager","APM"], location: "Sunnyvale, CA", remoteType: "hybrid", salaryRange: "$175k–$265k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://careers.linkedin.com", tags: ["Professional Network","B2B","PM"] },
  { id: "salesforce", name: "Salesforce", categories: ["faang","product"], skills: ["Apex","JavaScript","React","Java","Cloud","CRM","Python","Product Management"], roles: ["Software Engineer","Solution Engineer","Platform Developer","PM","Product Manager","Technical PM"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$165k–$250k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://careers.salesforce.com", tags: ["CRM","Enterprise","Cloud","PM"] },
  { id: "adobe", name: "Adobe", categories: ["faang","design","product"], skills: ["React","Java","Python","ML","C++","Creative","TypeScript","Product Design"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","UX Engineer","Product Manager","Group PM"], location: "San Jose, CA", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://adobe.com/careers", tags: ["Creative","Design","SaaS","PM"] },
  { id: "oracle", name: "Oracle", categories: ["faang"], skills: ["Java","SQL","Cloud","C","Python","Distributed Systems"], roles: ["Software Engineer","Cloud Engineer","Database Engineer","SRE","Product Manager"], location: "Austin, TX", remoteType: "hybrid", salaryRange: "$155k–$240k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://oracle.com/careers", tags: ["Database","Cloud","Enterprise"] },

  // ─── AI Labs ────────────────────────────────────────────────────────────
  { id: "openai", name: "OpenAI", categories: ["ai"], skills: ["Python","PyTorch","ML","LLMs","RLHF","React","TypeScript","Distributed Training"], roles: ["ML Engineer","Research Engineer","Software Engineer","Product Engineer","UI Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$200k–$400k", hiringIntensity: "high", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: false, url: "https://openai.com/careers", tags: ["AI","Top Tier","AGI"] },
  { id: "anthropic", name: "Anthropic", categories: ["ai"], skills: ["Python","PyTorch","ML","Safety","React","TypeScript","Distributed Systems"], roles: ["Research Engineer","ML Engineer","Software Engineer","UI Engineer","Safety Researcher"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$200k–$380k", hiringIntensity: "high", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: false, url: "https://anthropic.com/careers", tags: ["AI Safety","Top Tier","Research"] },
  { id: "perplexity", name: "Perplexity", categories: ["ai","yc"], skills: ["Python","React","TypeScript","LLMs","Search","System Design"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","Product Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$180k–$320k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: false, url: "https://perplexity.ai/careers", tags: ["AI Search","Fast Growing"] },
  { id: "mistral", name: "Mistral AI", categories: ["ai"], skills: ["Python","PyTorch","LLMs","Distributed Training","C++","CUDA"], roles: ["Research Engineer","ML Engineer","Software Engineer","Inference Engineer"], location: "Paris, France", remoteType: "hybrid", salaryRange: "€150k–€300k", hiringIntensity: "high", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://mistral.ai/careers", tags: ["AI","European","Open Source LLM"] },
  { id: "cohere", name: "Cohere", categories: ["ai"], skills: ["Python","NLP","ML","React","TypeScript","APIs"], roles: ["ML Engineer","Software Engineer","Frontend Engineer","Developer Advocate"], location: "Toronto, Canada", remoteType: "remote", salaryRange: "$160k–$280k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: true, url: "https://cohere.com/careers", tags: ["Enterprise AI","NLP"] },
  { id: "huggingface", name: "Hugging Face", categories: ["ai"], skills: ["Python","PyTorch","ML","React","TypeScript","Open Source","Transformers"], roles: ["ML Engineer","Software Engineer","Developer Advocate","Frontend Engineer"], location: "New York, NY", remoteType: "remote", salaryRange: "$150k–$270k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://huggingface.co/jobs", tags: ["Open Source AI","ML Community"] },
  { id: "databricks", name: "Databricks", categories: ["ai","infra"], skills: ["Python","Scala","Spark","SQL","ML","React","Java","Distributed Systems"], roles: ["Software Engineer","ML Engineer","Data Engineer","Solutions Architect"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$185k–$320k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://databricks.com/careers", tags: ["Data+AI","Lakehouse","Enterprise"] },
  { id: "scale_ai", name: "Scale AI", categories: ["ai"], skills: ["Python","React","TypeScript","ML","Data Pipelines","System Design"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","Data Platform Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$300k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: true, remoteFriendly: false, url: "https://scale.com/careers", tags: ["AI Data","Defense","Enterprise"] },
  { id: "together_ai", name: "Together AI", categories: ["ai"], skills: ["Python","CUDA","Distributed Training","React","Inference","C++"], roles: ["ML Engineer","Inference Engineer","Software Engineer","Research Scientist"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$180k–$320k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://together.ai/careers", tags: ["Inference","Open Source LLM"] },
  { id: "replicate", name: "Replicate", categories: ["ai","devtools"], skills: ["Python","Go","React","Docker","ML","APIs","TypeScript"], roles: ["Software Engineer","ML Engineer","Developer Advocate","Platform Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$160k–$270k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://replicate.com/jobs", tags: ["ML APIs","DevTools"] },
  { id: "runway", name: "Runway", categories: ["ai","design"], skills: ["Python","React","TypeScript","WebGL","ML","Video AI"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","Creative Tech"], location: "New York, NY", remoteType: "hybrid", salaryRange: "$160k–$280k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: false, url: "https://runwayml.com/careers", tags: ["Generative AI","Creative","Video"] },
  { id: "character_ai", name: "Character.AI", categories: ["ai"], skills: ["Python","PyTorch","React","TypeScript","LLMs","System Design"], roles: ["ML Engineer","Software Engineer","Frontend Engineer","Research Scientist"], location: "Menlo Park, CA", remoteType: "hybrid", salaryRange: "$180k–$320k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: false, url: "https://character.ai/careers", tags: ["AI Companions","Consumer AI"] },
  { id: "ideogram", name: "Ideogram", categories: ["ai"], skills: ["Python","PyTorch","React","TypeScript","Diffusion Models","Computer Vision"], roles: ["ML Engineer","Software Engineer","Frontend Engineer"], location: "Toronto, Canada", remoteType: "remote", salaryRange: "$160k–$280k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://ideogram.ai/careers", tags: ["Image AI","Generative"] },
  { id: "adept", name: "Adept AI", categories: ["ai"], skills: ["Python","PyTorch","React","TypeScript","Agents","System Design"], roles: ["Research Engineer","ML Engineer","Software Engineer"], location: "San Francisco, CA", remoteType: "onsite", salaryRange: "$180k–$350k", hiringIntensity: "medium", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "fast", internFriendly: false, remoteFriendly: false, url: "https://adept.ai/careers", tags: ["AI Agents","Foundation Models"] },
  { id: "deepmind", name: "Google DeepMind", categories: ["ai"], skills: ["Python","PyTorch","TensorFlow","RL","Research","Distributed Training","ML"], roles: ["Research Scientist","Research Engineer","Software Engineer","ML Engineer"], location: "London, UK", remoteType: "hybrid", salaryRange: "£120k–£250k", hiringIntensity: "medium", interviewDifficulty: "elite", aiAdoption: "native", growthVelocity: "fast", internFriendly: true, remoteFriendly: false, url: "https://deepmind.google/careers", tags: ["Research","RL","AGI"] },
  { id: "stability", name: "Stability AI", categories: ["ai"], skills: ["Python","PyTorch","Diffusion Models","React","CUDA","Open Source"], roles: ["ML Engineer","Research Scientist","Software Engineer","DevOps"], location: "London, UK", remoteType: "remote", salaryRange: "$140k–$280k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://stability.ai/careers", tags: ["Image AI","Open Source"] },

  // ─── SaaS / Productivity ────────────────────────────────────────────────
  { id: "notion", name: "Notion", categories: ["saas","design","product"], skills: ["React","TypeScript","Node.js","Electron","System Design","Collaboration","Product Thinking"], roles: ["Software Engineer","Frontend Engineer","iOS Engineer","Platform Engineer","Product Manager","APM","Growth PM"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$270k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://notion.so/careers", tags: ["Productivity","B2B","Design","PM"] },
  { id: "slack", name: "Slack (Salesforce)", categories: ["saas","product"], skills: ["React","Node.js","TypeScript","Java","Electron","WebSocket","Product Strategy"], roles: ["Software Engineer","Frontend Engineer","Platform Engineer","Mobile Engineer","Product Manager","Technical PM"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$260k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://slack.com/careers", tags: ["Collaboration","Enterprise","Messaging","PM"] },
  { id: "dropbox", name: "Dropbox", categories: ["saas"], skills: ["Python","React","TypeScript","Rust","Go","Distributed Systems"], roles: ["Software Engineer","Frontend Engineer","Infrastructure Engineer","Data Scientist","Product Manager"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$165k–$250k", hiringIntensity: "low", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://dropbox.com/jobs", tags: ["Remote-First","Storage","Collaboration"] },
  { id: "atlassian", name: "Atlassian", categories: ["saas","product"], skills: ["Java","React","TypeScript","Python","AWS","GraphQL","Product Management"], roles: ["Software Engineer","Frontend Engineer","Platform Engineer","SRE","Product Manager","Group PM"], location: "Austin, TX", remoteType: "remote", salaryRange: "$170k–$255k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://atlassian.com/company/careers", tags: ["DevTools","Collaboration","Enterprise","PM"] },
  { id: "asana", name: "Asana", categories: ["saas","product"], skills: ["Python","React","TypeScript","GraphQL","System Design","Product Thinking"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Data Engineer","Product Manager","APM"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$165k–$250k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://asana.com/jobs", tags: ["Productivity","Work Management","PM"] },
  { id: "hubspot", name: "HubSpot", categories: ["saas","product"], skills: ["Java","React","TypeScript","Python","SQL","HubL","Product Analytics"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Data Scientist","Product Manager","Growth PM"], location: "Cambridge, MA", remoteType: "hybrid", salaryRange: "$155k–$240k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://hubspot.com/careers", tags: ["CRM","Marketing","SMB","PM"] },
  { id: "zendesk", name: "Zendesk", categories: ["saas","product"], skills: ["Ruby","React","TypeScript","Go","Python","SQL","Product Management"], roles: ["Software Engineer","Frontend Engineer","ML Engineer","Infrastructure Engineer","Product Manager"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$160k–$245k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://zendesk.com/jobs", tags: ["CX","Customer Support","Enterprise","PM"] },
  { id: "clickup", name: "ClickUp", categories: ["saas","remote","product"], skills: ["React","TypeScript","Node.js","Python","MongoDB","Product Strategy"], roles: ["Frontend Engineer","Software Engineer","Mobile Engineer","QA Engineer","Product Manager","APM"], location: "San Diego, CA", remoteType: "remote", salaryRange: "$140k–$220k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://clickup.com/careers", tags: ["Productivity","Remote-First","Fast Growing","PM"] },
  { id: "intercom", name: "Intercom", categories: ["saas","product"], skills: ["Ruby","React","TypeScript","Ember.js","iOS","Android","Product Management"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","ML Engineer","Product Manager"], location: "Chicago, IL", remoteType: "hybrid", salaryRange: "$155k–$235k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://intercom.com/careers", tags: ["Customer Messaging","B2B SaaS","PM"] },
  { id: "monday", name: "Monday.com", categories: ["saas","product"], skills: ["React","Node.js","MongoDB","GraphQL","TypeScript","Python","Product Thinking"], roles: ["Software Engineer","Frontend Engineer","Full Stack Engineer","Mobile Engineer","Product Manager","Group PM"], location: "Tel Aviv, Israel", remoteType: "hybrid", salaryRange: "$140k–$220k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://monday.com/jobs", tags: ["Work OS","B2B","International","PM"] },

  // ─── DevTools / Infrastructure ──────────────────────────────────────────
  { id: "vercel", name: "Vercel", categories: ["devtools","remote"], skills: ["React","Next.js","TypeScript","Rust","Go","Edge Computing","Node.js"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","Runtime Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$155k–$240k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://vercel.com/careers", tags: ["Frontend","Next.js","Remote-First"] },
  { id: "cloudflare", name: "Cloudflare", categories: ["devtools","infra"], skills: ["Rust","Go","C","TypeScript","React","Networking","Workers"], roles: ["Software Engineer","Network Engineer","Security Engineer","Developer Advocate"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$165k–$260k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://cloudflare.com/careers", tags: ["Edge","Security","CDN"] },
  { id: "github", name: "GitHub", categories: ["devtools"], skills: ["Ruby","Go","TypeScript","React","Rust","Python","Git"], roles: ["Software Engineer","Frontend Engineer","Platform Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$175k–$265k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://github.com/careers", tags: ["DevTools","Open Source","Microsoft"] },
  { id: "gitlab", name: "GitLab", categories: ["devtools","remote"], skills: ["Ruby","Go","TypeScript","Vue.js","Python","DevOps"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","SRE"], location: "Remote", remoteType: "remote", salaryRange: "$150k–$240k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://gitlab.com/careers", tags: ["DevOps","Remote-First","Open Source"] },
  { id: "docker", name: "Docker", categories: ["devtools"], skills: ["Go","Rust","Linux","Containers","TypeScript","React"], roles: ["Software Engineer","Platform Engineer","Developer Advocate","Solutions Engineer"], location: "Palo Alto, CA", remoteType: "remote", salaryRange: "$145k–$220k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://docker.com/careers", tags: ["Containers","DevOps"] },
  { id: "supabase", name: "Supabase", categories: ["devtools","remote"], skills: ["TypeScript","React","Go","PostgreSQL","Rust","Open Source"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","Postgres Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$130k–$210k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://supabase.com/careers", tags: ["Open Source","BaaS","Remote-First"] },
  { id: "hashicorp", name: "HashiCorp", categories: ["devtools","infra"], skills: ["Go","Terraform","Python","React","TypeScript","Infrastructure as Code"], roles: ["Software Engineer","Solutions Engineer","Developer Advocate","Platform Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$160k–$250k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://hashicorp.com/jobs", tags: ["Infrastructure","DevOps","Cloud"] },
  { id: "datadog", name: "Datadog", categories: ["devtools","infra"], skills: ["Go","Python","React","TypeScript","Kubernetes","Distributed Systems"], roles: ["Software Engineer","Frontend Engineer","SRE","Solutions Engineer"], location: "New York, NY", remoteType: "hybrid", salaryRange: "$170k–$260k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://datadoghq.com/careers", tags: ["Observability","Monitoring","DevOps"] },
  { id: "grafana", name: "Grafana Labs", categories: ["devtools","remote"], skills: ["Go","TypeScript","React","Prometheus","SQL","Distributed Systems"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","SRE"], location: "Remote", remoteType: "remote", salaryRange: "$145k–$230k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://grafana.com/careers", tags: ["Observability","Open Source","Remote-First"] },
  { id: "sentry", name: "Sentry", categories: ["devtools"], skills: ["Python","TypeScript","React","Django","PostgreSQL","Celery"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","Backend Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$145k–$220k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://sentry.io/careers", tags: ["Error Tracking","Open Source","DevTools"] },
  { id: "linear", name: "Linear", categories: ["devtools","design"], skills: ["TypeScript","React","Node.js","GraphQL","Electron","MobX","WebSocket"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Backend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$165k–$255k", hiringIntensity: "low", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://linear.app/careers", tags: ["Design Focused","High Craft","Remote-First"] },
  { id: "planetscale", name: "PlanetScale", categories: ["devtools","remote"], skills: ["Go","MySQL","React","TypeScript","Vitess","Distributed Databases"], roles: ["Software Engineer","Database Engineer","Frontend Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$145k–$225k", hiringIntensity: "low", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://planetscale.com/careers", tags: ["Serverless DB","MySQL","Remote-First"] },
  { id: "neon", name: "Neon", categories: ["devtools","remote"], skills: ["Rust","Go","PostgreSQL","TypeScript","React","Distributed Systems"], roles: ["Software Engineer","Postgres Engineer","Frontend Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$140k–$220k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://neon.tech/jobs", tags: ["Serverless Postgres","Remote-First"] },
  { id: "turso", name: "Turso", categories: ["devtools","remote"], skills: ["Rust","SQLite","TypeScript","React","libSQL"], roles: ["Software Engineer","Developer Advocate","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$130k–$200k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://turso.tech/careers", tags: ["Edge Database","Open Source"] },
  { id: "fly_io", name: "Fly.io", categories: ["devtools","remote"], skills: ["Go","Rust","TypeScript","React","Linux","Distributed Systems"], roles: ["Software Engineer","Platform Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$140k–$210k", hiringIntensity: "low", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://fly.io/jobs", tags: ["App Hosting","Remote-First"] },
  { id: "tailscale", name: "Tailscale", categories: ["devtools","remote"], skills: ["Go","TypeScript","React","Networking","WireGuard","iOS","Android"], roles: ["Software Engineer","Network Engineer","Mobile Engineer","Security Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$145k–$225k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://tailscale.com/jobs", tags: ["Networking","Security","Remote-First"] },
  { id: "retool", name: "Retool", categories: ["devtools","saas"], skills: ["React","TypeScript","Node.js","GraphQL","Python","SQL"], roles: ["Software Engineer","Frontend Engineer","Solutions Engineer","Developer Advocate"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: false, url: "https://retool.com/careers", tags: ["Internal Tools","Low-Code","B2B"] },
  { id: "prisma", name: "Prisma", categories: ["devtools","remote"], skills: ["TypeScript","Rust","Node.js","React","SQL","GraphQL"], roles: ["Software Engineer","Developer Relations","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$135k–$205k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://prisma.io/jobs", tags: ["ORM","TypeScript","Open Source"] },

  // ─── Design / Creative Tech ─────────────────────────────────────────────
  { id: "figma", name: "Figma", categories: ["design","saas"], skills: ["C++","WebAssembly","TypeScript","React","WebGL","Rust","Node.js"], roles: ["Software Engineer","Platform Engineer","Creative Tech","Frontend Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$185k–$290k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://figma.com/careers", tags: ["Design","Collaboration","Deep Tech"] },
  { id: "framer", name: "Framer", categories: ["design","devtools"], skills: ["React","TypeScript","WebGL","Motion","CSS","Node.js"], roles: ["Software Engineer","Frontend Engineer","Creative Engineer","Designer-Engineer"], location: "Amsterdam, NL", remoteType: "remote", salaryRange: "$120k–$200k", hiringIntensity: "low", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://framer.com/careers", tags: ["Design Tools","No-Code","Animation"] },
  { id: "canva", name: "Canva", categories: ["design","saas"], skills: ["Java","TypeScript","React","Python","ML","iOS","Android"], roles: ["Software Engineer","Frontend Engineer","ML Engineer","Mobile Engineer"], location: "Sydney, Australia", remoteType: "hybrid", salaryRange: "$140k–$230k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://canva.com/careers", tags: ["Design","Consumer","Global"] },
  { id: "lottiefiles", name: "LottieFiles", categories: ["design","remote"], skills: ["React","TypeScript","Node.js","Animation","WebGL"], roles: ["Frontend Engineer","Software Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$90k–$160k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://lottiefiles.com/careers", tags: ["Animation","Design Tools"] },

  // ─── Fintech ────────────────────────────────────────────────────────────
  { id: "stripe", name: "Stripe", categories: ["fintech"], skills: ["Ruby","Java","TypeScript","React","Go","APIs","System Design","Payments"], roles: ["Software Engineer","Frontend Engineer","Infrastructure Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$185k–$290k", hiringIntensity: "high", interviewDifficulty: "elite", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://stripe.com/jobs", tags: ["Payments","API-First","Prestigious"] },
  { id: "plaid", name: "Plaid", categories: ["fintech"], skills: ["Go","React","TypeScript","Python","Banking APIs","System Design"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$265k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://plaid.com/careers", tags: ["Banking APIs","Open Finance"] },
  { id: "ramp", name: "Ramp", categories: ["fintech","yc"], skills: ["Python","React","TypeScript","Go","SQL","System Design"], roles: ["Software Engineer","Frontend Engineer","Data Engineer","ML Engineer"], location: "New York, NY", remoteType: "hybrid", salaryRange: "$175k–$270k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: false, url: "https://ramp.com/careers", tags: ["Corporate Cards","Expense","High Velocity"] },
  { id: "brex", name: "Brex", categories: ["fintech","yc"], skills: ["Elixir","React","TypeScript","Go","Python","System Design"], roles: ["Software Engineer","Frontend Engineer","Data Engineer","Platform Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$170k–$260k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://brex.com/careers", tags: ["Corporate Cards","Fintech","YC"] },
  { id: "mercury", name: "Mercury", categories: ["fintech"], skills: ["Haskell","TypeScript","React","PostgreSQL","Python"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Product Designer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$165k–$255k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://mercury.com/jobs", tags: ["Banking","Startup Friendly","Remote"] },
  { id: "robinhood", name: "Robinhood", categories: ["fintech"], skills: ["Python","Go","React","TypeScript","iOS","Android","Data"], roles: ["Software Engineer","Mobile Engineer","Data Engineer","ML Engineer"], location: "Menlo Park, CA", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://careers.robinhood.com", tags: ["Trading","Consumer Finance","Mobile"] },
  { id: "wise", name: "Wise", categories: ["fintech"], skills: ["Java","React","TypeScript","Python","SQL","Microservices"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Data Engineer"], location: "London, UK", remoteType: "hybrid", salaryRange: "£80k–£160k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://wise.com/careers", tags: ["Global Payments","International","UK"] },
  { id: "checkout", name: "Checkout.com", categories: ["fintech"], skills: ["Java","Go","React","TypeScript","SQL","Payments"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Platform Engineer"], location: "London, UK", remoteType: "hybrid", salaryRange: "$150k–$240k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://checkout.com/careers", tags: ["Payments","Global","Enterprise"] },
  { id: "coinbase", name: "Coinbase", categories: ["fintech"], skills: ["React","TypeScript","Go","Ruby","Python","Blockchain","iOS"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Blockchain Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$170k–$260k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://coinbase.com/careers", tags: ["Crypto","Exchange","Remote"] },
  { id: "navan", name: "Navan (TripActions)", categories: ["fintech","saas"], skills: ["Java","React","TypeScript","Go","Python","iOS","Android"], roles: ["Software Engineer","Mobile Engineer","Frontend Engineer","Data Engineer"], location: "Palo Alto, CA", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://navan.com/careers", tags: ["Corporate Travel","Expense","SaaS"] },

  // ─── Indian Startups / Tech ──────────────────────────────────────────────
  { id: "razorpay", name: "Razorpay", categories: ["fintech","indian"], skills: ["Java","Go","React","TypeScript","Python","Payments","Node.js"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","SRE"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹40L–₹100L", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://razorpay.com/jobs", tags: ["Payments","Indian Unicorn","Fintech"] },
  { id: "cred", name: "CRED", categories: ["fintech","indian"], skills: ["Kotlin","Swift","React","TypeScript","Python","Go","Data"], roles: ["Android Engineer","iOS Engineer","Frontend Engineer","Backend Engineer","Data Engineer"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹35L–₹90L", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: false, url: "https://cred.club/careers", tags: ["Fintech","Premium Design","Indian Unicorn"] },
  { id: "swiggy", name: "Swiggy", categories: ["indian"], skills: ["Java","Go","React","Python","Kafka","Kubernetes","iOS","Android"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","ML Engineer","Data Scientist"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹30L–₹80L", hiringIntensity: "very_high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://swiggy.com/careers", tags: ["Food Delivery","Indian Unicorn","Scale"] },
  { id: "zomato", name: "Zomato", categories: ["indian"], skills: ["Python","Go","React","TypeScript","Kafka","ML","Android","iOS"], roles: ["Software Engineer","ML Engineer","Data Scientist","Mobile Engineer","Backend Engineer"], location: "Gurugram, India", remoteType: "hybrid", salaryRange: "₹25L–₹70L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://careers.zomato.com", tags: ["Food Tech","Indian Unicorn","Consumer"] },
  { id: "zepto", name: "Zepto", categories: ["indian"], skills: ["React","Python","Node.js","Go","Kotlin","Swift","SQL"], roles: ["Software Engineer","Mobile Engineer","Frontend Engineer","Backend Engineer","Data Analyst"], location: "Mumbai, India", remoteType: "hybrid", salaryRange: "₹25L–₹65L", hiringIntensity: "very_high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: false, url: "https://zepto.com/careers", tags: ["Quick Commerce","Hypergrowth","Indian"] },
  { id: "groww", name: "Groww", categories: ["fintech","indian"], skills: ["Java","React","TypeScript","Kotlin","Swift","Python","Data"], roles: ["Software Engineer","Mobile Engineer","Frontend Engineer","Data Engineer","SRE"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹30L–₹75L", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: true, remoteFriendly: false, url: "https://groww.in/careers", tags: ["Investing","Fintech","Indian Unicorn"] },
  { id: "meesho", name: "Meesho", categories: ["indian"], skills: ["Java","React","Python","Go","Kotlin","iOS","Data"], roles: ["Software Engineer","ML Engineer","Data Scientist","Mobile Engineer","SRE"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹25L–₹65L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://meesho.com/careers", tags: ["Social Commerce","Indian Unicorn","Tier-2"] },
  { id: "phonepe", name: "PhonePe", categories: ["fintech","indian"], skills: ["Java","Go","React","Kotlin","Swift","Kafka","Data"], roles: ["Software Engineer","Mobile Engineer","Backend Engineer","Data Engineer","ML Engineer"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹30L–₹80L", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: false, url: "https://phonepe.com/careers", tags: ["Payments","UPI","Indian Unicorn"] },
  { id: "paytm", name: "Paytm", categories: ["fintech","indian"], skills: ["Java","React","Python","Go","Android","iOS","Data"], roles: ["Software Engineer","Mobile Engineer","Data Scientist","Backend Engineer"], location: "Noida, India", remoteType: "hybrid", salaryRange: "₹20L–₹60L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://paytm.com/careers", tags: ["Payments","Fintech","Indian"] },
  { id: "flipkart", name: "Flipkart", categories: ["indian"], skills: ["Java","React","Python","Kafka","Kubernetes","Spark","Data"], roles: ["Software Engineer","ML Engineer","Data Engineer","Platform Engineer","SDE"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹35L–₹90L", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://flipkartcareers.com", tags: ["E-Commerce","Scale","Indian"] },
  { id: "byju", name: "BYJU'S", categories: ["indian"], skills: ["React","Node.js","Python","iOS","Android","TypeScript"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Backend Engineer"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹15L–₹50L", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://byjus.com/jobs", tags: ["EdTech","Indian Unicorn","Consumer"] },
  { id: "ola", name: "Ola", categories: ["indian"], skills: ["Java","Python","React","Kotlin","iOS","Data","Kafka"], roles: ["Software Engineer","Mobile Engineer","Data Scientist","ML Engineer"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹25L–₹70L", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://ola.careers", tags: ["Mobility","Indian Unicorn","EV"] },
  { id: "dunzo", name: "Dunzo", categories: ["indian"], skills: ["Python","React","Node.js","Go","TypeScript"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Data Analyst"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹18L–₹45L", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://dunzo.com/careers", tags: ["Quick Commerce","Indian"] },
  { id: "freshworks", name: "Freshworks", categories: ["saas","indian"], skills: ["Ruby","React","TypeScript","Java","Python","SQL"], roles: ["Software Engineer","Frontend Engineer","Full Stack Engineer","ML Engineer"], location: "Chennai, India", remoteType: "hybrid", salaryRange: "₹25L–₹70L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://careers.freshworks.com", tags: ["SaaS","CX","Indian Listed"] },
  { id: "browserstack", name: "BrowserStack", categories: ["devtools","indian","remote"], skills: ["Node.js","React","TypeScript","Selenium","Java","Python","Ruby"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","QA Engineer"], location: "Remote", remoteType: "remote", salaryRange: "₹30L–₹80L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://browserstack.com/careers", tags: ["Testing","DevTools","Indian Unicorn"] },
  { id: "postman", name: "Postman", categories: ["devtools","indian"], skills: ["React","Node.js","TypeScript","Electron","Go","Python"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","Backend Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$155k–$240k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://postman.com/company/careers", tags: ["API Tools","DevTools","Indian-Founded"] },
  { id: "chargebee", name: "Chargebee", categories: ["saas","indian"], skills: ["Java","React","TypeScript","Node.js","Ruby","SQL"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Solutions Engineer"], location: "Chennai, India", remoteType: "hybrid", salaryRange: "₹20L–₹55L", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://chargebee.com/careers", tags: ["Billing","SaaS","Indian Unicorn"] },
  { id: "slintel", name: "Leadsquared", categories: ["saas","indian"], skills: ["Java","React","Python","SQL","TypeScript","Node.js"], roles: ["Software Engineer","Frontend Engineer","Data Engineer"], location: "Bengaluru, India", remoteType: "hybrid", salaryRange: "₹15L–₹40L", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://leadsquared.com/careers", tags: ["CRM","Sales","Indian SaaS"] },

  // ─── YC Startups ────────────────────────────────────────────────────────
  { id: "openbb", name: "OpenBB", categories: ["yc","fintech"], skills: ["Python","React","TypeScript","Data","Finance"], roles: ["Software Engineer","Data Engineer","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$120k–$190k", hiringIntensity: "low", interviewDifficulty: "medium", aiAdoption: "native", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://openbb.co/careers", tags: ["Open Source","Finance","YC"] },
  { id: "descript", name: "Descript", categories: ["yc","ai"], skills: ["React","TypeScript","Python","Electron","WebAssembly","ML"], roles: ["Software Engineer","ML Engineer","Frontend Engineer","Audio Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$155k–$235k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: false, remoteFriendly: false, url: "https://descript.com/careers", tags: ["Audio/Video AI","Editing","YC"] },
  { id: "loom", name: "Loom (Atlassian)", categories: ["yc","saas"], skills: ["React","TypeScript","Node.js","Go","WebRTC","Chrome Extension"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Growth Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$160k–$240k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://loom.com/jobs", tags: ["Video Messaging","Async","YC"] },
  { id: "deel", name: "Deel", categories: ["yc","fintech","remote"], skills: ["React","TypeScript","Node.js","Python","PostgreSQL"], roles: ["Software Engineer","Frontend Engineer","Full Stack Engineer","Mobile Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$130k–$210k", hiringIntensity: "very_high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://deel.com/careers", tags: ["Global Payroll","HR Tech","YC","Remote-First"] },
  { id: "pave", name: "Pave", categories: ["yc","saas"], skills: ["Ruby","React","TypeScript","PostgreSQL","GraphQL"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$155k–$235k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: false, url: "https://pave.com/careers", tags: ["Compensation","HR Tech","YC"] },
  { id: "supertokens", name: "SuperTokens", categories: ["yc","devtools","remote"], skills: ["Node.js","Go","React","TypeScript","PostgreSQL","Auth"], roles: ["Software Engineer","Developer Advocate","Backend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$100k–$170k", hiringIntensity: "low", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://supertokens.com/careers", tags: ["Auth","Open Source","YC"] },
  { id: "cal_com", name: "Cal.com", categories: ["yc","remote","devtools"], skills: ["TypeScript","React","Next.js","Prisma","Node.js"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$100k–$170k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://cal.com/careers", tags: ["Scheduling","Open Source","YC"] },
  { id: "resend", name: "Resend", categories: ["yc","devtools","remote"], skills: ["TypeScript","React","Node.js","Email","APIs"], roles: ["Software Engineer","Developer Advocate","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$100k–$170k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: false, remoteFriendly: true, url: "https://resend.com/careers", tags: ["Email API","DevTools","YC"] },

  // ─── Cloud / Infrastructure ─────────────────────────────────────────────
  { id: "aws", name: "Amazon Web Services", categories: ["infra"], skills: ["Java","Python","Go","C++","Distributed Systems","Networking","TypeScript"], roles: ["Software Engineer","Cloud Engineer","SRE","Infrastructure Engineer"], location: "Seattle, WA", remoteType: "hybrid", salaryRange: "$175k–$270k", hiringIntensity: "very_high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "established", internFriendly: true, remoteFriendly: true, url: "https://aws.amazon.com/careers", tags: ["Cloud","Infrastructure","Scale"] },
  { id: "gcp", name: "Google Cloud", categories: ["infra"], skills: ["Go","Python","C++","Java","Kubernetes","TypeScript","Distributed Systems"], roles: ["Software Engineer","Cloud Engineer","Developer Advocate","Solutions Architect"], location: "Sunnyvale, CA", remoteType: "hybrid", salaryRange: "$180k–$280k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "native", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://careers.google.com/teams/google-cloud", tags: ["Cloud","Kubernetes","DevOps"] },
  { id: "digitalocean", name: "DigitalOcean", categories: ["infra","remote"], skills: ["Go","TypeScript","React","Python","Kubernetes","PostgreSQL"], roles: ["Software Engineer","Frontend Engineer","Platform Engineer","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$145k–$225k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://digitalocean.com/careers", tags: ["Cloud","SMB","Remote-First"] },
  { id: "mongodb", name: "MongoDB", categories: ["infra","devtools"], skills: ["C++","Java","Go","Python","React","TypeScript","Node.js"], roles: ["Software Engineer","Developer Advocate","Solutions Architect","Frontend Engineer"], location: "New York, NY", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://mongodb.com/careers", tags: ["Database","Document DB","Developer Focused"] },
  { id: "redis", name: "Redis", categories: ["infra","devtools"], skills: ["C","Rust","Go","TypeScript","React","Distributed Systems"], roles: ["Software Engineer","Developer Advocate","Solutions Engineer","Frontend Engineer"], location: "Mountain View, CA", remoteType: "hybrid", salaryRange: "$155k–$240k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://redis.com/careers", tags: ["Cache","In-Memory DB","Open Source"] },
  { id: "confluent", name: "Confluent", categories: ["infra"], skills: ["Java","Kafka","Python","Go","React","TypeScript","Distributed Systems"], roles: ["Software Engineer","Data Engineer","Solutions Architect","Developer Advocate"], location: "Mountain View, CA", remoteType: "remote", salaryRange: "$165k–$255k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://confluent.io/careers", tags: ["Streaming","Kafka","Data"] },
  { id: "elastic", name: "Elastic", categories: ["infra","remote"], skills: ["Java","Go","React","TypeScript","Elasticsearch","Python","Kibana"], roles: ["Software Engineer","Frontend Engineer","Solutions Architect","Developer Advocate"], location: "Remote", remoteType: "remote", salaryRange: "$155k–$240k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://elastic.co/careers", tags: ["Search","Observability","Open Source"] },
  { id: "snowflake", name: "Snowflake", categories: ["infra"], skills: ["Java","Python","Scala","SQL","React","TypeScript","Cloud"], roles: ["Software Engineer","Data Engineer","ML Engineer","Solutions Engineer"], location: "San Mateo, CA", remoteType: "hybrid", salaryRange: "$175k–$280k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://snowflake.com/careers", tags: ["Data Cloud","Analytics","Enterprise"] },

  // ─── Communication / Collaboration ──────────────────────────────────────
  { id: "zoom", name: "Zoom", categories: ["saas"], skills: ["C++","Java","React","TypeScript","iOS","Android","WebRTC"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Platform Engineer"], location: "San Jose, CA", remoteType: "hybrid", salaryRange: "$160k–$250k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://zoom.us/careers", tags: ["Video Conferencing","Enterprise","Remote"] },
  { id: "twilio", name: "Twilio", categories: ["devtools","saas"], skills: ["Java","Python","React","TypeScript","Node.js","APIs","Telecom"], roles: ["Software Engineer","Developer Advocate","Frontend Engineer","Solutions Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$160k–$250k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://twilio.com/company/jobs", tags: ["Communications","API","DevTools"] },
  { id: "sendgrid", name: "SendGrid (Twilio)", categories: ["devtools","saas"], skills: ["Python","Go","React","TypeScript","Email","APIs","Node.js"], roles: ["Software Engineer","Developer Advocate","Platform Engineer"], location: "Denver, CO", remoteType: "remote", salaryRange: "$150k–$235k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://sendgrid.com/careers", tags: ["Email API","DevTools"] },
  { id: "discord", name: "Discord", categories: ["saas"], skills: ["Python","Rust","TypeScript","React","iOS","Android","WebRTC"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$265k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://discord.com/jobs", tags: ["Community","Gaming","Consumer"] },

  // ─── E-Commerce / Consumer ──────────────────────────────────────────────
  { id: "shopify", name: "Shopify", categories: ["saas","remote"], skills: ["Ruby","React","TypeScript","Go","GraphQL","iOS","Android"], roles: ["Software Engineer","Frontend Engineer","Mobile Engineer","Platform Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$155k–$240k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://shopify.com/careers", tags: ["E-Commerce","Remote-First","Merchant"] },
  { id: "doordash", name: "DoorDash", categories: ["faang"], skills: ["Python","Go","React","TypeScript","Kotlin","iOS","Kafka"], roles: ["Software Engineer","Frontend Engineer","ML Engineer","Data Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$265k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://doordash.com/careers", tags: ["Delivery","Marketplace","Scale"] },
  { id: "instacart", name: "Instacart", categories: ["saas"], skills: ["Ruby","Python","React","TypeScript","Go","Data"], roles: ["Software Engineer","ML Engineer","Data Scientist","Frontend Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$165k–$255k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://instacart.com/careers", tags: ["Grocery","Marketplace","Consumer"] },

  // ─── Security ───────────────────────────────────────────────────────────
  { id: "crowdstrike", name: "CrowdStrike", categories: ["infra"], skills: ["Go","C++","React","Python","TypeScript","Kubernetes","Security"], roles: ["Software Engineer","Security Engineer","Frontend Engineer","Cloud Engineer"], location: "Austin, TX", remoteType: "remote", salaryRange: "$165k–$260k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://crowdstrike.com/careers", tags: ["Cybersecurity","Endpoint","Enterprise"] },
  { id: "okta", name: "Okta", categories: ["infra","saas"], skills: ["Java","React","TypeScript","Python","OAuth","SAML","Node.js"], roles: ["Software Engineer","Frontend Engineer","Security Engineer","Solutions Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$160k–$255k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://okta.com/company/careers", tags: ["Identity","Auth","Enterprise"] },
  { id: "1password", name: "1Password", categories: ["saas","remote"], skills: ["Rust","Go","Swift","Kotlin","React","TypeScript","Security"], roles: ["Software Engineer","Security Engineer","Mobile Engineer","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$150k–$235k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://1password.com/careers", tags: ["Security","Password Manager","Remote-First"] },

  // ─── Miscellaneous Premium ──────────────────────────────────────────────
  { id: "spotify", name: "Spotify", categories: ["faang"], skills: ["Java","Python","React","TypeScript","Kotlin","iOS","Data","Kafka"], roles: ["Software Engineer","Backend Engineer","Data Engineer","ML Engineer","Frontend Engineer"], location: "Stockholm, Sweden", remoteType: "hybrid", salaryRange: "SEK 700k–1.5M", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://lifeatspotify.com", tags: ["Music","Consumer","International"] },
  { id: "stripe_press", name: "Liveblocks", categories: ["devtools","remote"], skills: ["TypeScript","React","Node.js","WebSocket","CRDT","WebRTC"], roles: ["Software Engineer","Developer Advocate","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$130k–$200k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://liveblocks.io/careers", tags: ["Real-Time","Collaboration","Remote"] },
  { id: "sanity", name: "Sanity.io", categories: ["devtools","remote"], skills: ["TypeScript","React","Node.js","JavaScript","GraphQL","GROQ"], roles: ["Software Engineer","Developer Advocate","Frontend Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$125k–$195k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://sanity.io/careers", tags: ["CMS","Headless","Remote-First"] },
  { id: "contentful", name: "Contentful", categories: ["saas"], skills: ["TypeScript","React","Node.js","GraphQL","Python","Go"], roles: ["Software Engineer","Frontend Engineer","Developer Advocate","Solutions Engineer"], location: "Berlin, Germany", remoteType: "hybrid", salaryRange: "€80k–€150k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://contentful.com/careers", tags: ["CMS","Headless","European"] },
  { id: "pagerduty", name: "PagerDuty", categories: ["infra","saas"], skills: ["Ruby","Go","React","TypeScript","Python","Incident Management"], roles: ["Software Engineer","Frontend Engineer","SRE","Platform Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$155k–$240k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://pagerduty.com/careers", tags: ["Incident Management","On-Call","Enterprise"] },
  { id: "mixpanel", name: "Mixpanel", categories: ["saas"], skills: ["Python","React","TypeScript","Go","SQL","Data Analytics"], roles: ["Software Engineer","Frontend Engineer","Data Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "remote", salaryRange: "$150k–$235k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "steady", internFriendly: false, remoteFriendly: true, url: "https://mixpanel.com/jobs", tags: ["Analytics","Product Analytics","B2B"] },
  { id: "airtable", name: "Airtable", categories: ["saas"], skills: ["TypeScript","React","Node.js","Python","Go","GraphQL"], roles: ["Software Engineer","Frontend Engineer","Platform Engineer","ML Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$170k–$260k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://airtable.com/careers", tags: ["No-Code","Database","Collaboration"] },
  { id: "webflow", name: "Webflow", categories: ["saas","design","remote"], skills: ["TypeScript","React","Node.js","CSS","Animation","WebGL"], roles: ["Software Engineer","Frontend Engineer","Designer-Engineer","Platform Engineer"], location: "Remote", remoteType: "remote", salaryRange: "$145k–$230k", hiringIntensity: "medium", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://webflow.com/careers", tags: ["No-Code","Design","Remote-First"] },
  { id: "rippling", name: "Rippling", categories: ["saas","yc"], skills: ["Python","React","TypeScript","Node.js","Ruby","GraphQL"], roles: ["Software Engineer","Frontend Engineer","Full Stack Engineer","Mobile Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$175k–$265k", hiringIntensity: "high", interviewDifficulty: "hard", aiAdoption: "heavy", growthVelocity: "hypergrowth", internFriendly: true, remoteFriendly: false, url: "https://rippling.com/careers", tags: ["HR Tech","Payroll","Platform"] },
  { id: "lattice", name: "Lattice", categories: ["saas"], skills: ["TypeScript","React","Node.js","Ruby","GraphQL","SQL"], roles: ["Software Engineer","Frontend Engineer","Backend Engineer","Data Engineer"], location: "San Francisco, CA", remoteType: "hybrid", salaryRange: "$155k–$235k", hiringIntensity: "medium", interviewDifficulty: "medium", aiAdoption: "heavy", growthVelocity: "fast", internFriendly: false, remoteFriendly: true, url: "https://lattice.com/careers", tags: ["People Management","HR Tech"] },
  { id: "toast", name: "Toast", categories: ["saas"], skills: ["Java","React","TypeScript","Android","Python","SQL"], roles: ["Software Engineer","Mobile Engineer","Frontend Engineer","Data Engineer"], location: "Boston, MA", remoteType: "hybrid", salaryRange: "$155k–$245k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "fast", internFriendly: true, remoteFriendly: true, url: "https://toast.com/careers", tags: ["Restaurant Tech","POS","Vertical SaaS"] },
  { id: "gusto", name: "Gusto", categories: ["saas","fintech"], skills: ["Ruby","React","TypeScript","Python","Go","SQL"], roles: ["Software Engineer","Frontend Engineer","Full Stack Engineer","Data Engineer"], location: "Denver, CO", remoteType: "hybrid", salaryRange: "$160k–$250k", hiringIntensity: "high", interviewDifficulty: "medium", aiAdoption: "moderate", growthVelocity: "steady", internFriendly: true, remoteFriendly: true, url: "https://gusto.com/careers", tags: ["Payroll","HR","SMB"] },
];

// ─── Lookup helpers ──────────────────────────────────────────────────────────

export function getCompaniesBySkills(skills: string[], limit = 40): Company[] {
  const normalized = skills.map(s => s.toLowerCase());
  const scored = COMPANIES.map(c => {
    const overlap = c.skills.filter(s => normalized.some(us => s.toLowerCase().includes(us) || us.includes(s.toLowerCase()))).length;
    return { company: c, score: overlap };
  }).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map(({ company }) => company);
}

export function getCompaniesByCategory(category: string, limit = 20): Company[] {
  return COMPANIES.filter(c => c.categories.includes(category)).slice(0, limit);
}

export function getPersonalizedPool(profile: {
  skills?: string[];
  careerGoal?: string;
  location?: string;
  remotePreference?: boolean;
}, count = 12): Company[] {
  const { skills = [], careerGoal = "", remotePreference } = profile;

  // Detect role category — comprehensive product/PM detection
  const goalLower = careerGoal.toLowerCase();
  const isProduct = goalLower.includes("product") || goalLower.includes(" pm") || goalLower.startsWith("pm") || goalLower.includes("apm") || goalLower.includes("product manager") || goalLower.includes("product management") || goalLower.includes("product engineer");
  let categoryBoost: string[] = [];
  if (isProduct) categoryBoost = ["product","saas","design"];
  else if (goalLower.includes("ai") || goalLower.includes("ml") || goalLower.includes("machine")) categoryBoost = ["ai"];
  else if (goalLower.includes("frontend") || goalLower.includes("ui") || goalLower.includes("react")) categoryBoost = ["devtools","design"];
  else if (goalLower.includes("fullstack") || goalLower.includes("full stack") || goalLower.includes("full-stack")) categoryBoost = ["saas","devtools"];
  else if (goalLower.includes("backend") || goalLower.includes("infra")) categoryBoost = ["infra","devtools"];
  else if (goalLower.includes("fintech") || goalLower.includes("finance")) categoryBoost = ["fintech"];
  else if (goalLower.includes("india") || goalLower.includes("indian")) categoryBoost = ["indian"];

  // Score all companies
  const normalizedSkills = skills.map(s => s.toLowerCase());
  const scored = COMPANIES.map(company => {
    let score = 0;
    // Skill overlap
    score += company.skills.filter(s => normalizedSkills.some(us => s.toLowerCase().includes(us) || us.includes(s.toLowerCase()))).length * 3;
    // Category boost
    if (categoryBoost.some(cat => company.categories.includes(cat))) score += 5;
    // Remote preference
    if (remotePreference && company.remoteFriendly) score += 2;
    // Intern friendly bonus
    if (company.internFriendly) score += 1;
    // Some randomness to avoid repetition
    score += Math.random() * 2;
    return { company, score };
  });

  // Shuffle top results to avoid always showing same companies
  const top = scored.sort((a, b) => b.score - a.score).slice(0, count * 2);
  const shuffled = top.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(({ company }) => company);
}

export function generateOpportunityFromCompany(company: Company, targetRole: string): {
  id: string;
  company: string;
  role: string;
  location: string;
  remote_type: string;
  salary_range: string;
  skills_required: string[];
  experience_level: string;
  url: string;
  tags: string[];
  hiringIntensity: string;
  remoteFriendly: boolean;
  internFriendly: boolean;
  interviewDifficulty: string;
  growthVelocity: string;
} {
  // Pick the most relevant role for the user's target — comprehensive matching
  const goalLower = targetRole.toLowerCase();
  const isProductGoal = goalLower.includes("product") || goalLower.includes(" pm") || goalLower.startsWith("pm") || goalLower.includes("apm");
  let bestRole = company.roles[0];

  for (const role of company.roles) {
    const roleLower = role.toLowerCase();
    // Product / PM matching — highest priority
    if (isProductGoal && (roleLower.includes("product manager") || roleLower.includes("apm") || roleLower === "pm" || roleLower.includes("growth pm"))) { bestRole = role; break; }
    if (isProductGoal && roleLower.includes("product")) { bestRole = role; continue; }
    // Engineering speciality matching
    if (goalLower.includes("frontend") && roleLower.includes("frontend")) { bestRole = role; break; }
    if (goalLower.includes("ml") && roleLower.includes("ml")) { bestRole = role; break; }
    if (goalLower.includes("backend") && roleLower.includes("backend")) { bestRole = role; break; }
    if (goalLower.includes("full") && roleLower.includes("full")) { bestRole = role; break; }
    if (goalLower.includes("ai") && (roleLower.includes("ml") || roleLower.includes("ai"))) { bestRole = role; break; }
    if (goalLower.includes("data") && roleLower.includes("data")) { bestRole = role; break; }
    if (goalLower.includes("mobile") && roleLower.includes("mobile")) { bestRole = role; break; }
    if (goalLower.includes("ios") && roleLower.includes("ios")) { bestRole = role; break; }
    if (goalLower.includes("android") && roleLower.includes("android")) { bestRole = role; break; }
  }

  return {
    id: `${company.id}_${bestRole.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 20)}`,
    company: company.name,
    role: bestRole,
    location: company.location,
    remote_type: company.remoteType,
    salary_range: company.salaryRange,
    skills_required: company.skills.slice(0, 5),
    experience_level: "mid",
    url: company.url,
    tags: company.tags,
    hiringIntensity: company.hiringIntensity,
    remoteFriendly: company.remoteFriendly,
    internFriendly: company.internFriendly,
    interviewDifficulty: company.interviewDifficulty,
    growthVelocity: company.growthVelocity,
  };
}
