import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#5b4137",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#e4beb2",
        secondary: "#75584d",
        "surface-dim": "#dbdcc3",
        "on-secondary-fixed": "#2b160f",
        "tertiary-container": "#4c4542",
        background: "#fbfbe2",
        "surface-container-highest": "#e4e4cc",
        "tertiary-fixed": "#ece0dc",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#e7bdb1",
        "on-surface-variant": "#504441",
        "on-surface": "#1b1d0e",
        outline: "#827470",
        "on-primary-fixed-variant": "#5d4037",
        surface: "#fbfbe2",
        "surface-container-high": "#eaead1",
        "inverse-primary": "#e7bdb1",
        "tertiary-fixed-dim": "#cfc4c0",
        "on-primary-fixed": "#2c160e",
        "inverse-on-surface": "#f2f2d9",
        "secondary-fixed": "#ffdbce",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbfbe2",
        primary: "#442a22",
        "on-primary": "#ffffff",
        "secondary-container": "#fed7ca",
        "on-tertiary-container": "#bdb3af",
        "on-secondary-container": "#795c51",
        "on-tertiary-fixed-variant": "#4c4542",
        "surface-tint": "#77574d",
        "primary-fixed": "#ffdbd0",
        "surface-variant": "#e4e4cc",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#d4ada1",
        "surface-container-low": "#f5f5dc",
        "error-container": "#ffdad6",
        "primary-container": "#5d4037",
        "on-error": "#ffffff",
        tertiary: "#352f2c",
        "surface-container": "#efefd7",
        "on-secondary": "#ffffff",
        "outline-variant": "#d4c3be",
        "inverse-surface": "#303221",
        "on-background": "#1b1d0e",
        "on-tertiary-fixed": "#201a18",
        "electric-blue": "#3b82f6",
        "muted-indigo": "#6366f1",
        "soft-lavender": "#a78bfa",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.4rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        base: "4px",
        "margin-desktop": "32px",
        gutter: "24px",
        xl: "48px",
        xs: "4px",
        "margin-mobile": "16px",
        sm: "8px",
        lg: "24px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
      },
    },
  },
  plugins: [],
};

export default config;
